import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { X, Briefcase, Building2, User, FileText, CheckCircle, UserCheck, TrendingUp, Share2, Info, Plus } from 'lucide-react';
import { Lead, LeadStatus, ClientType, LeadCategory } from '../../../types';
import FormInput from '../../common/FormInput';
import { db } from '../../../firebase';
import { collection, getDocs } from 'firebase/firestore';
import { fetchCRMCompanies, addCRMCompany } from '../../../services/crmService';
import toast from 'react-hot-toast';

const getClientTypeConfig = (type: ClientType) => {
  switch (type) {
    case ClientType.B2B:
      return {
        label: 'Company Name',
        placeholder: 'e.g. Acme Technologies Inc.',
        hint: 'Specify which company this B2B client belongs to',
        icon: Building2,
        badgeColor: 'bg-blue-50 text-blue-700 border-blue-200'
      };
    case ClientType.FRIEND:
      return {
        label: 'Friend Name',
        placeholder: "e.g. John Doe (Friend)",
        hint: 'Specify the friend who referred or connected this lead',
        icon: UserCheck,
        badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200'
      };
    case ClientType.SALES:
      return {
        label: 'Sales Representative / Person',
        placeholder: 'e.g. Select from sales team or type name',
        hint: 'Specify the sales member or representative',
        icon: TrendingUp,
        badgeColor: 'bg-purple-50 text-purple-700 border-purple-200'
      };
    case ClientType.REFERRAL:
      return {
        label: 'Referrer Name (Reference)',
        placeholder: 'e.g. Referred by Jane Smith',
        hint: 'Specify who gave the reference for this client',
        icon: Share2,
        badgeColor: 'bg-amber-50 text-amber-700 border-amber-200'
      };
    case ClientType.OTHER:
    default:
      return {
        label: 'Reference / Source Details',
        placeholder: 'e.g. Exhibition, Walk-in, Social campaign',
        hint: 'Specify additional details or reference origin',
        icon: Info,
        badgeColor: 'bg-slate-50 text-slate-700 border-slate-200'
      };
  }
};

interface LeadFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: Omit<Lead, 'id' | 'createdAt' | 'updatedAt'>) => Promise<void>;
  initialData?: Lead | null;
  autoGeneratedSlNo: string;
  defaultCategory?: LeadCategory;
}

export const LeadFormModal: React.FC<LeadFormModalProps> = ({ isOpen, onClose, onSubmit, initialData, autoGeneratedSlNo, defaultCategory = LeadCategory.COMPANY }) => {
  const defaultFormData: Omit<Lead, 'id' | 'createdAt' | 'updatedAt'> = {
    slNo: autoGeneratedSlNo,
    category: defaultCategory,
    projectName: '',
    firstStartDate: '',
    workCommencementDate: '',
    status: LeadStatus.PENDING,
    pocName: '',
    pocEmail: '',
    pocPhone: '',
    clientName: '',
    clientPhone: '',
    clientEmail: '',
    clientType: ClientType.B2B,
    clientTypeDetail: '',
    department: [],
    domainDetail: '',
    expiryDate: '',
    remark: '',
    assignedTo: ''
  };

  const [formData, setFormData] = useState(defaultFormData);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [departmentInput, setDepartmentInput] = useState('');
  const [salesUsers, setSalesUsers] = useState<{id: string, name: string}[]>([]);
  const [companies, setCompanies] = useState<string[]>([]);
  const [isAddingCompany, setIsAddingCompany] = useState(false);
  const [newCompanyInput, setNewCompanyInput] = useState('');
  const [isSavingCompany, setIsSavingCompany] = useState(false);

  useEffect(() => {
    const fetchSalesUsers = async () => {
      try {
        const usersRef = collection(db, 'users');
        const snapshot = await getDocs(usersRef);
        const fetchedUsers = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() as any }));
        const sales = fetchedUsers.filter(u => u.department === 'Sales');
        setSalesUsers(sales.map(u => ({ id: u.id, name: u.name })));
      } catch (e) {
        console.error('Failed to fetch sales users', e);
      }
    };
    fetchSalesUsers();
  }, []);

  useEffect(() => {
    const loadCompanies = async () => {
      try {
        const list = await fetchCRMCompanies();
        setCompanies(list);
      } catch (e) {
        console.error('Failed to load CRM companies', e);
      }
    };
    if (isOpen) {
      loadCompanies();
      setIsAddingCompany(false);
      setNewCompanyInput('');
    }
  }, [isOpen]);

  useEffect(() => {
    if (isOpen) {
      if (initialData) {
        setFormData({
          ...initialData,
          category: initialData.category || LeadCategory.COMPANY,
          clientTypeDetail: initialData.clientTypeDetail || ''
        });
      } else {
        setFormData({ ...defaultFormData, slNo: autoGeneratedSlNo, category: defaultCategory, clientTypeDetail: '' });
      }
      setDepartmentInput('');
    }
  }, [isOpen, initialData, autoGeneratedSlNo, defaultCategory]);

  const handleSaveNewCompany = async () => {
    const trimmed = newCompanyInput.trim();
    if (!trimmed) {
      toast.error('Please enter a company name');
      return;
    }
    setIsSavingCompany(true);
    try {
      await addCRMCompany(trimmed);
      setCompanies(prev => {
        const set = new Set([...prev, trimmed]);
        return Array.from(set).sort((a, b) => a.localeCompare(b));
      });
      setFormData(prev => ({ ...prev, clientTypeDetail: trimmed }));
      setNewCompanyInput('');
      setIsAddingCompany(false);
      toast.success(`Company "${trimmed}" selected!`);
    } catch (e: any) {
      console.warn('Fallback setting company locally:', e);
      setCompanies(prev => Array.from(new Set([...prev, trimmed])).sort((a, b) => a.localeCompare(b)));
      setFormData(prev => ({ ...prev, clientTypeDetail: trimmed }));
      setNewCompanyInput('');
      setIsAddingCompany(false);
      toast.success(`Company "${trimmed}" selected!`);
    } finally {
      setIsSavingCompany(false);
    }
  };

  if (!isOpen) return null;

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Auto-save new company if user was typing in the Add Company box and hit submit directly
    let finalClientTypeDetail = formData.clientTypeDetail;
    if (formData.clientType === ClientType.B2B && isAddingCompany && newCompanyInput.trim()) {
      const trimmedCompany = newCompanyInput.trim();
      try {
        await addCRMCompany(trimmedCompany);
      } catch {}
      finalClientTypeDetail = trimmedCompany;
    }

    setIsSubmitting(true);
    try {
      await onSubmit({
        ...formData,
        clientTypeDetail: finalClientTypeDetail
      });
      onClose();
    } catch (error) {
      console.error('Failed to submit lead', error);
      toast.error('Failed to save lead. Please check network and try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleAddDepartment = () => {
    if (departmentInput.trim() && !formData.department.includes(departmentInput.trim())) {
      setFormData({
        ...formData,
        department: [...formData.department, departmentInput.trim()]
      });
      setDepartmentInput('');
    }
  };

  const handleRemoveDepartment = (dept: string) => {
    setFormData({
      ...formData,
      department: formData.department.filter(d => d !== dept)
    });
  };

  return createPortal(
    <div 
      onClick={onClose}
      className="fixed inset-0 bg-transparent flex justify-center items-center z-[9999] p-4 animate-in fade-in duration-200"
    >
      <div 
        onClick={(e) => e.stopPropagation()}
        className="bg-white rounded-2xl shadow-2xl border border-slate-200 p-0 w-full max-w-2xl m-4 max-h-[90vh] overflow-hidden flex flex-col animate-in zoom-in-95 duration-200"
      >
        
        {/* Modal Header */}
        <div className="flex justify-between items-center px-8 py-6 border-b border-slate-100 flex-shrink-0">
          <div>
            <h3 className="text-xl font-bold text-slate-900">{initialData ? 'Edit Lead' : 'Add New Lead'}</h3>
            <p className="text-sm text-slate-500">{initialData ? 'Update lead details' : 'Create a new CRM lead'}</p>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-slate-50 rounded-full text-slate-400 hover:text-slate-900 transition-colors">
            <X size={24} />
          </button>
        </div>

        {/* Modal Content */}
        <form id="lead-form" onSubmit={handleSubmit} className="flex-1 overflow-y-auto custom-scrollbar p-8 pt-6">
          <div className="space-y-8">
            
            {/* General Info */}
            <div className="space-y-5">
              <div className="flex items-center gap-2 mb-2">
                <Briefcase size={16} className="text-indigo-600" />
                <h4 className="text-sm font-bold text-slate-900 uppercase tracking-widest">General Information</h4>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <FormInput 
                  label="SL No" 
                  name="slNo" 
                  value={formData.slNo} 
                  onChange={handleInputChange} 
                  required 
                  readOnly 
                  className="!bg-slate-100 !text-slate-500 cursor-not-allowed font-mono" 
                />
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Lead Type / Category</label>
                  <select
                    name="category"
                    value={formData.category || LeadCategory.COMPANY}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 rounded-xl border-slate-200 bg-slate-50/50 focus:border-indigo-500 transition-all outline-none font-medium text-slate-700"
                  >
                    {Object.values(LeadCategory).map((cat) => (
                      <option key={cat} value={cat}>{cat} Lead</option>
                    ))}
                  </select>
                </div>
                <FormInput 
                  label="Project Name" 
                  name="projectName" 
                  value={formData.projectName} 
                  onChange={handleInputChange} 
                  placeholder="e.g. Website Redesign" 
                />
                <FormInput 
                  label="First Start Date" 
                  name="firstStartDate" 
                  type="date" 
                  value={formData.firstStartDate} 
                  onChange={handleInputChange} 
                />
                <FormInput 
                  label="Work Commencement Date" 
                  name="workCommencementDate" 
                  type="date" 
                  value={formData.workCommencementDate || ''} 
                  onChange={handleInputChange} 
                />
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Assigned Member (Sales)</label>
                  <select
                    name="assignedTo"
                    value={formData.assignedTo || ''}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 rounded-xl border-slate-200 bg-slate-50/50 focus:border-indigo-500 transition-all outline-none font-medium text-slate-700"
                  >
                    <option value="">Unassigned</option>
                    {salesUsers.map((user) => (
                      <option key={user.id} value={user.id}>{user.name}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center">
                    Status
                  </label>
                  <select
                    name="status"
                    value={formData.status}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 rounded-xl border-slate-200 bg-slate-50/50 focus:border-indigo-500 transition-all outline-none font-medium text-slate-700"
                  >
                    {Object.values(LeadStatus).map((status) => (
                      <option key={status} value={status}>{status}</option>
                    ))}
                  </select>
                </div>
              </div>
            </div>

            {/* Point of Contact */}
            <div className="space-y-5">
              <div className="flex items-center gap-2 mb-2">
                <User size={16} className="text-indigo-600" />
                <h4 className="text-sm font-bold text-slate-900 uppercase tracking-widest">Point of Contact</h4>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <FormInput 
                  label="POC Name" 
                  name="pocName" 
                  value={formData.pocName} 
                  onChange={handleInputChange} 
                  placeholder="John Doe" 
                />
                <FormInput 
                  label="POC Email" 
                  name="pocEmail" 
                  type="email" 
                  value={formData.pocEmail} 
                  onChange={handleInputChange} 
                  placeholder="john@example.com" 
                />
                <FormInput 
                  label="POC Phone" 
                  name="pocPhone" 
                  type="tel" 
                  value={formData.pocPhone} 
                  onChange={handleInputChange} 
                  placeholder="+1 234 567 8900" 
                />
              </div>
            </div>

            {/* Client Details */}
            <div className="space-y-5">
              <div className="flex items-center gap-2 mb-2">
                <Building2 size={16} className="text-indigo-600" />
                <h4 className="text-sm font-bold text-slate-900 uppercase tracking-widest">Client Details</h4>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <FormInput 
                  label="Client Name" 
                  name="clientName" 
                  value={formData.clientName} 
                  onChange={handleInputChange} 
                  placeholder="Acme Corp" 
                />
                <FormInput 
                  label="Client Phone" 
                  name="clientPhone" 
                  type="tel" 
                  value={formData.clientPhone} 
                  onChange={handleInputChange} 
                  placeholder="+1 234 567 8900" 
                />
                <FormInput 
                  label="Client Email" 
                  name="clientEmail" 
                  type="email" 
                  value={formData.clientEmail} 
                  onChange={handleInputChange} 
                  placeholder="client@company.com" 
                />
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center">
                    Client Type
                  </label>
                  <select
                    name="clientType"
                    value={formData.clientType}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 rounded-xl border-slate-200 bg-slate-50/50 focus:border-indigo-500 transition-all outline-none font-medium text-slate-700"
                  >
                    {Object.values(ClientType).map((type) => (
                      <option key={type} value={type}>{type}</option>
                    ))}
                  </select>
                </div>

                {/* Dynamic Client Type Detail Field */}
                {(() => {
                  const clientTypeConfig = getClientTypeConfig(formData.clientType);
                  const ConfigIcon = clientTypeConfig.icon;
                  const isB2B = formData.clientType === ClientType.B2B;

                  return (
                    <div className="md:col-span-2 p-4 rounded-xl border border-indigo-100/80 bg-indigo-50/30 transition-all animate-in fade-in duration-200">
                      <div className="flex items-center justify-between mb-2">
                        <label htmlFor="clientTypeDetail" className="block text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
                          <ConfigIcon size={15} className="text-indigo-600" />
                          {clientTypeConfig.label}
                        </label>
                        <span className={`text-[11px] font-bold px-2.5 py-0.5 rounded-full border ${clientTypeConfig.badgeColor}`}>
                          {formData.clientType}
                        </span>
                      </div>

                      {isB2B ? (
                        isAddingCompany ? (
                          <div className="space-y-2 bg-white p-3.5 rounded-xl border border-indigo-200 shadow-sm animate-in zoom-in-95 duration-150">
                            <div className="flex items-center justify-between text-xs font-bold text-indigo-900">
                              <span>Add New Company</span>
                              <button
                                type="button"
                                onClick={() => { setIsAddingCompany(false); setNewCompanyInput(''); }}
                                className="text-slate-400 hover:text-slate-600 p-1"
                              >
                                <X size={14} />
                              </button>
                            </div>
                            <div className="flex gap-2">
                              <input
                                type="text"
                                value={newCompanyInput}
                                onChange={(e) => setNewCompanyInput(e.target.value)}
                                placeholder="Enter company name..."
                                autoFocus
                                onKeyDown={(e) => {
                                  if (e.key === 'Enter') {
                                    e.preventDefault();
                                    handleSaveNewCompany();
                                  }
                                }}
                                className="flex-1 px-3.5 py-2.5 rounded-lg border border-slate-300 bg-slate-50 focus:bg-white focus:border-indigo-500 text-sm font-medium text-slate-800 outline-none transition-all"
                              />
                              <button
                                type="button"
                                onClick={handleSaveNewCompany}
                                disabled={!newCompanyInput.trim() || isSavingCompany}
                                className="px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold transition-all disabled:opacity-50 flex items-center gap-1.5 shadow-sm shadow-indigo-200"
                              >
                                {isSavingCompany ? 'Saving...' : 'Save & Select'}
                              </button>
                              <button
                                type="button"
                                onClick={() => { setIsAddingCompany(false); setNewCompanyInput(''); }}
                                className="px-3 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-lg text-xs font-bold transition-all"
                              >
                                Cancel
                              </button>
                            </div>
                          </div>
                        ) : (
                          <div className="flex gap-2">
                            <div className="relative flex-1">
                              <select
                                id="clientTypeDetail"
                                name="clientTypeDetail"
                                value={formData.clientTypeDetail || ''}
                                onChange={(e) => {
                                  if (e.target.value === '__add_new__') {
                                    setIsAddingCompany(true);
                                  } else {
                                    handleInputChange(e);
                                  }
                                }}
                                className="w-full px-4 py-3 rounded-xl border border-slate-200 bg-white focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 transition-all outline-none font-medium text-slate-700 text-sm shadow-sm"
                              >
                                <option value="">-- Select Company --</option>
                                {companies.map((comp) => (
                                  <option key={comp} value={comp}>{comp}</option>
                                ))}
                                {formData.clientTypeDetail && !companies.includes(formData.clientTypeDetail) && (
                                  <option value={formData.clientTypeDetail}>{formData.clientTypeDetail} (Custom)</option>
                                )}
                                <option value="__add_new__" className="text-indigo-600 font-bold">
                                  ➕ + Add New Company...
                                </option>
                              </select>
                            </div>
                            <button
                              type="button"
                              onClick={() => setIsAddingCompany(true)}
                              className="px-3.5 py-2.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-600 rounded-xl text-xs font-bold border border-indigo-200 transition-all flex items-center gap-1.5 flex-shrink-0 shadow-sm"
                              title="Add a new company to directory"
                            >
                              <Plus size={14} /> Add New
                            </button>
                          </div>
                        )
                      ) : (
                        <>
                          <input
                            id="clientTypeDetail"
                            name="clientTypeDetail"
                            list={formData.clientType === ClientType.SALES ? "sales-team-datalist" : undefined}
                            value={formData.clientTypeDetail || ''}
                            onChange={handleInputChange}
                            placeholder={clientTypeConfig.placeholder}
                            className="w-full px-4 py-3 rounded-xl border border-slate-200 bg-white focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 transition-all outline-none font-medium text-slate-700 placeholder:text-slate-400 text-sm shadow-sm"
                          />
                          {formData.clientType === ClientType.SALES && (
                            <datalist id="sales-team-datalist">
                              {salesUsers.map(user => (
                                <option key={user.id} value={user.name} />
                              ))}
                            </datalist>
                          )}
                        </>
                      )}

                      <p className="text-xs text-slate-500 mt-2 flex items-center gap-1.5">
                        <Info size={13} className="text-indigo-500 flex-shrink-0" />
                        {clientTypeConfig.hint}
                      </p>
                    </div>
                  );
                })()}
              </div>
            </div>

            {/* Additional Details */}
            <div className="space-y-5">
              <div className="flex items-center gap-2 mb-2">
                <FileText size={16} className="text-indigo-600" />
                <h4 className="text-sm font-bold text-slate-900 uppercase tracking-widest">Additional Details</h4>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <FormInput 
                  label="Domain Detail" 
                  name="domainDetail" 
                  value={formData.domainDetail} 
                  onChange={handleInputChange} 
                  placeholder="e.g. www.example.com" 
                />
                <FormInput 
                  label="Expiry Date" 
                  name="expiryDate" 
                  type="date" 
                  value={formData.expiryDate || ''} 
                  onChange={handleInputChange} 
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Departments</label>
                <div className="flex gap-2 mb-2">
                  <select
                    value={departmentInput}
                    onChange={(e) => setDepartmentInput(e.target.value)}
                    className="flex-1 px-4 py-3 rounded-xl border-slate-200 bg-slate-50/50 focus:border-indigo-500 transition-all outline-none font-medium text-slate-700 border"
                  >
                    <option value="">Select Department...</option>
                    <option value="SEO">SEO</option>
                    <option value="Development">Development</option>
                    <option value="Product">Product</option>
                    <option value="Media">Media</option>
                    <option value="Sales">Sales</option>
                    <option value="Visitor">Visitor</option>
                  </select>
                  <button
                    type="button"
                    onClick={handleAddDepartment}
                    disabled={!departmentInput}
                    className="px-6 py-2.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 rounded-xl font-bold transition-all disabled:opacity-50"
                  >
                    Add
                  </button>
                </div>
                <div className="flex flex-wrap gap-2">
                  {formData.department.map(dept => (
                    <span key={dept} className="inline-flex items-center gap-1 px-3 py-1 bg-slate-100 text-slate-700 rounded-full text-sm font-medium">
                      {dept}
                      <button
                        type="button"
                        onClick={() => handleRemoveDepartment(dept)}
                        className="text-slate-400 hover:text-red-500 transition-colors"
                      >
                        <X size={14} />
                      </button>
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Remark</label>
                <textarea
                  name="remark"
                  rows={3}
                  value={formData.remark}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 rounded-xl border-slate-200 bg-slate-50/50 focus:border-indigo-500 transition-all outline-none font-medium text-slate-700 border resize-none"
                  placeholder="Any additional remarks..."
                ></textarea>
              </div>
            </div>
          </div>
        </form>

        {/* Modal Footer */}
        <div className="px-8 py-6 bg-slate-50 border-t border-slate-100 flex justify-end gap-3">
          <button
            type="button"
            onClick={onClose}
            className="px-6 py-2.5 text-slate-600 font-bold hover:bg-slate-100 rounded-xl transition-all"
            disabled={isSubmitting}
          >
            Cancel
          </button>
          <button
            type="submit"
            form="lead-form"
            disabled={isSubmitting}
            className="px-8 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-bold shadow-lg shadow-indigo-200 transition-all active:scale-95 disabled:opacity-50"
          >
            {isSubmitting ? 'Saving...' : (initialData ? 'Update Lead' : 'Add Lead')}
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
};
