/**
 * File: components/admin/crm/LeadFormModal.tsx
 * Purpose: Modal dialog for creating and updating leads with validation and company auto-save.
 * Author: Hirush Global AMS
 */

import React, { useState, useEffect, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { X } from 'lucide-react';
import { Lead, LeadStatus, ClientType, LeadCategory } from '../../../types';
import { db } from '../../../firebase';
import { collection, getDocs } from 'firebase/firestore';
import { fetchCRMCompanies, addCRMCompany } from '../../../services/crmService';
import toast from 'react-hot-toast';
import { LeadFormGeneralSection } from './LeadFormGeneralSection';
import { LeadFormClientSection } from './LeadFormClientSection';
import { LeadFormProjectSection } from './LeadFormProjectSection';

interface LeadFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: Omit<Lead, 'id' | 'createdAt' | 'updatedAt'>) => Promise<void>;
  initialData?: Lead | null;
  autoGeneratedSlNo: string;
  defaultCategory?: LeadCategory;
}

export const LeadFormModal: React.FC<LeadFormModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
  initialData,
  autoGeneratedSlNo,
  defaultCategory = LeadCategory.COMPANY,
}) => {
  const defaultFormData: Omit<Lead, 'id' | 'createdAt' | 'updatedAt'> = useMemo(() => ({
    slNo: autoGeneratedSlNo,
    category: defaultCategory,
    projectName: '',
    firstStartDate: '',
    workCommencementDate: '',
    status: LeadStatus.PENDING,
    pocName: '',
    pocEmail: '',
    pocPhone: '',
    clientName: '',
    clientPhone: '',
    clientEmail: '',
    clientType: ClientType.B2B,
    clientTypeDetail: '',
    department: [],
    domainDetail: '',
    expiryDate: '',
    remark: '',
    assignedTo: '',
  }), [autoGeneratedSlNo, defaultCategory]);

  const [formData, setFormData] = useState(defaultFormData);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [departmentInput, setDepartmentInput] = useState('');
  const [salesUsers, setSalesUsers] = useState<{ id: string; name: string }[]>([]);
  const [companies, setCompanies] = useState<string[]>([]);
  const [isAddingCompany, setIsAddingCompany] = useState(false);
  const [newCompanyInput, setNewCompanyInput] = useState('');
  const [isSavingCompany, setIsSavingCompany] = useState(false);

  useEffect(() => {
    const fetchSalesUsers = async () => {
      try {
        const snapshot = await getDocs(collection(db, 'users'));
        const fetched = snapshot.docs.map((d) => ({ id: d.id, ...(d.data() as any) }));
        setSalesUsers(fetched.filter((u) => u.department === 'Sales').map((u) => ({ id: u.id, name: u.name })));
      } catch (e) {
        console.error('Failed to fetch sales users', e);
      }
    };
    fetchSalesUsers();
  }, []);

  useEffect(() => {
    if (isOpen) {
      fetchCRMCompanies().then(setCompanies).catch(console.error);
      setIsAddingCompany(false);
      setNewCompanyInput('');
      if (initialData) {
        setFormData({
          ...initialData,
          category: initialData.category || LeadCategory.COMPANY,
          clientTypeDetail: initialData.clientTypeDetail || '',
        });
      } else {
        setFormData(defaultFormData);
      }
      setDepartmentInput('');
    }
  }, [isOpen, initialData, defaultFormData]);

  const handleSaveNewCompany = async () => {
    const trimmed = newCompanyInput.trim();
    if (!trimmed) {
      toast.error('Please enter a company name');
      return;
    }
    setIsSavingCompany(true);
    try {
      await addCRMCompany(trimmed);
      setCompanies((prev) => Array.from(new Set([...prev, trimmed])).sort((a, b) => a.localeCompare(b)));
      setFormData((prev) => ({ ...prev, clientTypeDetail: trimmed }));
      setNewCompanyInput('');
      setIsAddingCompany(false);
      toast.success(`Company "${trimmed}" selected!`);
    } catch {
      setCompanies((prev) => Array.from(new Set([...prev, trimmed])).sort((a, b) => a.localeCompare(b)));
      setFormData((prev) => ({ ...prev, clientTypeDetail: trimmed }));
      setNewCompanyInput('');
      setIsAddingCompany(false);
      toast.success(`Company "${trimmed}" selected!`);
    } finally {
      setIsSavingCompany(false);
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    let finalClientTypeDetail = formData.clientTypeDetail;
    if (formData.clientType === ClientType.B2B && isAddingCompany && newCompanyInput.trim()) {
      const trimmedCompany = newCompanyInput.trim();
      try {
        await addCRMCompany(trimmedCompany);
      } catch {
        /* company already cached or offline */
      }
      finalClientTypeDetail = trimmedCompany;
    }

    setIsSubmitting(true);
    try {
      await onSubmit({ ...formData, clientTypeDetail: finalClientTypeDetail });
      onClose();
    } catch {
      toast.error('Failed to save lead. Please check network and try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleAddDepartment = () => {
    if (departmentInput.trim() && !formData.department.includes(departmentInput.trim())) {
      setFormData({ ...formData, department: [...formData.department, departmentInput.trim()] });
      setDepartmentInput('');
    }
  };

  const handleRemoveDepartment = (dept: string) => {
    setFormData({ ...formData, department: formData.department.filter((d) => d !== dept) });
  };

  if (!isOpen) return null;

  return createPortal(
    <div onClick={onClose} className="fixed inset-0 bg-transparent flex justify-center items-center z-[9999] p-4 animate-in fade-in duration-200">
      <div onClick={(e) => e.stopPropagation()} className="bg-white rounded-2xl shadow-2xl border border-slate-200 p-0 w-full max-w-2xl m-4 max-h-[90vh] overflow-hidden flex flex-col animate-in zoom-in-95 duration-200">
        <div className="flex justify-between items-center px-8 py-6 border-b border-slate-100 flex-shrink-0">
          <div>
            <h3 className="text-xl font-bold text-slate-900">{initialData ? 'Edit Lead' : 'Add New Lead'}</h3>
            <p className="text-sm text-slate-500">{initialData ? 'Update lead details' : 'Create a new CRM lead'}</p>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-slate-50 rounded-full text-slate-400 hover:text-slate-900 transition-colors">
            <X size={24} />
          </button>
        </div>

        <form id="lead-form" onSubmit={handleSubmit} className="flex-1 overflow-y-auto custom-scrollbar p-8 pt-6">
          <div className="space-y-8">
            <LeadFormGeneralSection formData={formData} onChange={handleInputChange} />
            <LeadFormClientSection
              formData={formData}
              onChange={handleInputChange}
              companies={companies}
              isAddingCompany={isAddingCompany}
              setIsAddingCompany={setIsAddingCompany}
              newCompanyInput={newCompanyInput}
              setNewCompanyInput={setNewCompanyInput}
              handleSaveNewCompany={handleSaveNewCompany}
              isSavingCompany={isSavingCompany}
              salesUsers={salesUsers}
            />
            <LeadFormProjectSection
              formData={formData}
              onChange={handleInputChange}
              salesUsers={salesUsers}
              departmentInput={departmentInput}
              setDepartmentInput={setDepartmentInput}
              onAddDepartment={handleAddDepartment}
              onRemoveDepartment={handleRemoveDepartment}
            />
          </div>
        </form>

        <div className="px-8 py-6 bg-slate-50 border-t border-slate-100 flex justify-end gap-3">
          <button type="button" onClick={onClose} className="px-6 py-2.5 text-slate-600 font-bold hover:bg-slate-100 rounded-xl transition-all" disabled={isSubmitting}>
            Cancel
          </button>
          <button type="submit" form="lead-form" disabled={isSubmitting} className="px-8 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-bold shadow-lg shadow-indigo-200 transition-all active:scale-95 disabled:opacity-50">
            {isSubmitting ? 'Saving...' : initialData ? 'Update Lead' : 'Add Lead'}
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
};

export default LeadFormModal;
